#!/bin/bash

#cd ~/Desktop/researchwork
 
./6_1comb_dt_make | ./runshellfindDT | ./newidentifyknot

## This just runs all the programs into each other. The cd line makes it
## so that it always calls the files from the right spot.
