#!/bin/bash
while read line
do 
 IFS=';'; combined=(${line}); unset IFS
 dt=$combined
 ogvector=${combined[1]}
 james=$(echo $dt | sed 's/ //g' | sed 's/,]/]/g')
 length=${#james}
 if [ $james == "comp" ]; then continue 
## Skip if the length if the dt notation is shorter than the 9-crossing knots 
 elif [ "$length" -lt "20" ]; then continue 
 else 
  line=$(cat smallestTable | grep -F $james)
  if [ -z "$line" ]; then continue; fi
## Tests if dt notation is in table, if not just skips to next one without writing
  cat smallestTable | grep -F $james | awk -F '&' '{print $1 ", " $2 ", "}' | tr -d "\n"
  echo $ogvector
 fi
done

## This takes takes a reduced DT notation, finds where it lives in 
## the table, and then outputs the first two columns of that row, 
## which are the two names of the knot.
## If it sees comp, it will translate that to Composite Knot.
