#!/bin/bash
   notation=$1
   var=`echo $notation | bin/shellfind /tmp/testout`

   if [[ "$var" != "" ]] ; then
      echo $var
   else 
      echo "comp"
   fi

## This program takes the unreduced DT notation and plugs it into shellfind.
## It then outputs the reduced form, but if it's a composite knot, it will 
## say comp. This will later be changed.

## Everything after this is when we wanted a timeout safeguard to stop
## the program from running indefinitely.

#&


#  mainpid=$!

#  sh -c "sleep $timeout 2>/dev/null; 2>>/dev/null kill $mainpid" &
#  timeoutpid=$!

#  wait $mainpid 2>/dev/null

#  if kill $timeoutpid 2>/dev/null ; then
#    continue 
#   else
#    echo "TIMEOUT"
#  fi 


